# Generated by Django 5.0 on 2026-01-23 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0014_aadharverification"),
        ("tournaments", "0017_alter_hostrating_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "merchant_order_id",
                    models.CharField(help_text="Unique order ID for merchant", max_length=100, unique=True),
                ),
                ("transaction_id", models.CharField(blank=True, help_text="PhonePe transaction ID", max_length=100)),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("tournament_plan", "Tournament Plan Payment"),
                            ("scrim_plan", "Scrim Plan Payment"),
                            ("tournament_entry", "Tournament Entry Fee"),
                            ("scrim_entry", "Scrim Entry Fee"),
                            ("refund", "Refund"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "payment_gateway",
                    models.CharField(
                        choices=[("phonepe", "PhonePe"), ("manual", "Manual")], default="phonepe", max_length=20
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, help_text="Amount in INR", max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("initiated", "Initiated"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "phonepe_response",
                    models.JSONField(blank=True, default=dict, help_text="Complete PhonePe response data"),
                ),
                (
                    "payment_instrument",
                    models.JSONField(blank=True, default=dict, help_text="Payment instrument details (UPI, Card, etc)"),
                ),
                ("initiated_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("error_code", models.CharField(blank=True, max_length=50)),
                ("error_message", models.TextField(blank=True)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="accounts.playerprofile",
                    ),
                ),
                (
                    "registration",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="tournaments.tournamentregistration",
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="tournaments.tournament",
                    ),
                ),
            ],
            options={
                "db_table": "payments",
                "ordering": ["-initiated_at"],
            },
        ),
        migrations.CreateModel(
            name="Refund",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "merchant_refund_id",
                    models.CharField(help_text="Unique refund ID for merchant", max_length=100, unique=True),
                ),
                (
                    "phonepe_refund_id",
                    models.CharField(blank=True, help_text="PhonePe refund transaction ID", max_length=100),
                ),
                (
                    "refund_amount",
                    models.DecimalField(decimal_places=2, help_text="Refund amount in INR", max_digits=10),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("initiated", "Initiated"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("reason", models.TextField(help_text="Reason for refund")),
                (
                    "phonepe_response",
                    models.JSONField(blank=True, default=dict, help_text="Complete PhonePe refund response"),
                ),
                ("initiated_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("error_code", models.CharField(blank=True, max_length=50)),
                ("error_message", models.TextField(blank=True)),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="refunds", to="payments.payment"
                    ),
                ),
            ],
            options={
                "db_table": "refunds",
                "ordering": ["-initiated_at"],
            },
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["merchant_order_id"], name="payments_merchan_c6b9a5_idx"),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["transaction_id"], name="payments_transac_a1f824_idx"),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["status"], name="payments_status_d621e5_idx"),
        ),
        migrations.AddIndex(
            model_name="refund",
            index=models.Index(fields=["merchant_refund_id"], name="refunds_merchan_8206e1_idx"),
        ),
        migrations.AddIndex(
            model_name="refund",
            index=models.Index(fields=["status"], name="refunds_status_2569d8_idx"),
        ),
    ]
