# Generated by Django 5.0 on 2026-01-23 17:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0014_aadharverification"),
        ("payments", "0001_initial"),
        ("tournaments", "0017_alter_hostrating_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="payment",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="refund",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveIndex(
            model_name="payment",
            name="payments_transac_a1f824_idx",
        ),
        migrations.RenameField(
            model_name="payment",
            old_name="initiated_at",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="refund",
            old_name="refund_amount",
            new_name="amount",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="error_message",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="payment_gateway",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="payment_instrument",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="phonepe_response",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="player",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="transaction_id",
        ),
        migrations.RemoveField(
            model_name="refund",
            name="error_message",
        ),
        migrations.RemoveField(
            model_name="refund",
            name="initiated_at",
        ),
        migrations.RemoveField(
            model_name="refund",
            name="phonepe_response",
        ),
        migrations.AddField(
            model_name="payment",
            name="amount_paisa",
            field=models.IntegerField(default=0, help_text="Amount in paisa (for PhonePe API)"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="payment",
            name="callback_data",
            field=models.JSONField(blank=True, default=dict, help_text="Complete callback response from PhonePe"),
        ),
        migrations.AddField(
            model_name="payment",
            name="detailed_error_code",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="payment",
            name="host_profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to="accounts.hostprofile",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="instrument_type",
            field=models.CharField(blank=True, help_text="ACCOUNT, CREDIT_CARD, DEBIT_CARD, etc.", max_length=50),
        ),
        migrations.AddField(
            model_name="payment",
            name="meta_info",
            field=models.JSONField(blank=True, default=dict, help_text="Additional metadata (udf1-5)"),
        ),
        migrations.AddField(
            model_name="payment",
            name="payment_mode",
            field=models.CharField(blank=True, help_text="UPI, Card, NetBanking, etc.", max_length=50),
        ),
        migrations.AddField(
            model_name="payment",
            name="phonepe_order_id",
            field=models.CharField(blank=True, help_text="Order ID generated by PhonePe", max_length=100),
        ),
        migrations.AddField(
            model_name="payment",
            name="phonepe_transaction_id",
            field=models.CharField(blank=True, help_text="Transaction ID from PhonePe", max_length=100),
        ),
        migrations.AddField(
            model_name="payment",
            name="player_profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to="accounts.playerprofile",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="redirect_url",
            field=models.URLField(blank=True, help_text="PhonePe checkout URL"),
        ),
        migrations.AddField(
            model_name="payment",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="refund",
            name="amount_paisa",
            field=models.IntegerField(default=0, help_text="Refund amount in paisa"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="refund",
            name="callback_data",
            field=models.JSONField(blank=True, default=dict, help_text="Complete callback response from PhonePe"),
        ),
        migrations.AddField(
            model_name="refund",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="refund",
            name="detailed_error_code",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="payment",
            name="merchant_order_id",
            field=models.CharField(help_text="Unique order ID generated by us", max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_type",
            field=models.CharField(
                choices=[
                    ("tournament_plan", "Tournament Plan"),
                    ("scrim_plan", "Scrim Plan"),
                    ("entry_fee", "Entry Fee"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="registration",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to="tournaments.tournamentregistration",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[("pending", "Pending"), ("completed", "Completed"), ("failed", "Failed")],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="tournament",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to="tournaments.tournament",
            ),
        ),
        migrations.AlterField(
            model_name="refund",
            name="merchant_refund_id",
            field=models.CharField(help_text="Unique refund ID generated by us", max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="refund",
            name="phonepe_refund_id",
            field=models.CharField(blank=True, help_text="Refund ID generated by PhonePe", max_length=100),
        ),
        migrations.AlterField(
            model_name="refund",
            name="reason",
            field=models.TextField(blank=True, help_text="Reason for refund"),
        ),
        migrations.AlterField(
            model_name="refund",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["phonepe_order_id"], name="payments_phonepe_311df9_idx"),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["user", "payment_type"], name="payments_user_id_de337b_idx"),
        ),
        migrations.AddIndex(
            model_name="refund",
            index=models.Index(fields=["phonepe_refund_id"], name="refunds_phonepe_0b5bc8_idx"),
        ),
    ]
