# Generated by Django 5.0 on 2026-01-26 12:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0006_seed_plan_pricing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="callback_data",
            field=models.JSONField(
                blank=True, default=dict, help_text="Complete callback response from PhonePe", null=True
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="instrument_type",
            field=models.CharField(
                blank=True, help_text="ACCOUNT, CREDIT_CARD, DEBIT_CARD, etc.", max_length=50, null=True
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_mode",
            field=models.CharField(blank=True, help_text="UPI, Card, NetBanking, etc.", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="phonepe_order_id",
            field=models.CharField(blank=True, help_text="Order ID generated by PhonePe", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="phonepe_transaction_id",
            field=models.CharField(blank=True, help_text="Transaction ID from PhonePe", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="redirect_url",
            field=models.TextField(blank=True, help_text="PhonePe checkout URL", null=True),
        ),
        migrations.AlterField(
            model_name="refund",
            name="callback_data",
            field=models.JSONField(
                blank=True, default=dict, help_text="Complete callback response from PhonePe", null=True
            ),
        ),
        migrations.AlterField(
            model_name="refund",
            name="phonepe_refund_id",
            field=models.CharField(blank=True, help_text="Refund ID generated by PhonePe", max_length=255, null=True),
        ),
    ]
