# Generated by Django 5.0 on 2025-11-07 17:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tournaments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="discord_id",
            field=models.CharField(blank=True, help_text="Discord server ID (optional)", max_length=100),
        ),
        migrations.AddField(
            model_name="tournament",
            name="rounds",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Round structure: [{round: 1, max_teams: 100}, {round: 2, qualifying_teams: 50}, ...]",
            ),
        ),
        migrations.AddField(
            model_name="tournament",
            name="tournament_date",
            field=models.DateField(blank=True, help_text="Tournament date", null=True),
        ),
        migrations.AddField(
            model_name="tournament",
            name="tournament_file",
            field=models.FileField(
                blank=True, help_text="Tournament rules PDF or document", null=True, upload_to="tournaments/files/"
            ),
        ),
        migrations.AddField(
            model_name="tournament",
            name="tournament_time",
            field=models.TimeField(blank=True, help_text="Tournament start time", null=True),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="banner_image",
            field=models.ImageField(
                blank=True, help_text="Tournament banner image (max 5MB)", null=True, upload_to="tournaments/banners/"
            ),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="description",
            field=models.TextField(help_text="Tournament description"),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="game_mode",
            field=models.CharField(choices=[("Squad", "Squad"), ("Duo", "Duo"), ("Solo", "Solo")], max_length=100),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="game_name",
            field=models.CharField(
                choices=[
                    ("BGMI", "BGMI"),
                    ("Valorant", "Valorant"),
                    ("COD", "Call of Duty"),
                    ("Freefire", "Free Fire"),
                    ("CS2", "Counter-Strike 2"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="max_participants",
            field=models.IntegerField(help_text="Maximum number of teams"),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="prize_distribution",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="rules",
            field=models.TextField(help_text="Custom rules and regulations"),
        ),
    ]
