# Generated by Django 5.0 on 2025-12-28 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_team_teammember"),
        ("tournaments", "0006_add_tournament_plans"),
    ]

    operations = [
        migrations.AddField(
            model_name="scrimregistration",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="scrim_registrations",
                to="accounts.team",
            ),
        ),
        migrations.AddField(
            model_name="tournamentregistration",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tournament_registrations",
                to="accounts.team",
            ),
        ),
    ]
