# Generated by Django 5.0 on 2025-12-28 13:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tournaments", "0007_scrimregistration_team_tournamentregistration_team"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scrimregistration",
            name="in_game_details",
        ),
        migrations.RemoveField(
            model_name="tournamentregistration",
            name="in_game_details",
        ),
    ]
