# Generated by Django 5.0 on 2025-12-30 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tournaments", "0008_remove_scrimregistration_in_game_details_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="use_groups_system",
            field=models.BooleanField(
                default=True, help_text="Use new groups and matches system (False for legacy tournaments)"
            ),
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("round_number", models.IntegerField()),
                ("group_name", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "teams",
                    models.ManyToManyField(related_name="tournament_groups", to="tournaments.tournamentregistration"),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="groups", to="tournaments.tournament"
                    ),
                ),
            ],
            options={
                "db_table": "tournament_groups",
                "ordering": ["round_number", "group_name"],
                "unique_together": {("tournament", "round_number", "group_name")},
            },
        ),
        migrations.CreateModel(
            name="Match",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("match_number", models.IntegerField()),
                ("match_id", models.CharField(blank=True, help_text="Room ID for the match", max_length=100)),
                (
                    "match_password",
                    models.CharField(blank=True, help_text="Password for the match room", max_length=100),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("waiting", "Waiting"), ("ongoing", "Ongoing"), ("completed", "Completed")],
                        default="waiting",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="matches", to="tournaments.group"
                    ),
                ),
            ],
            options={
                "db_table": "tournament_matches",
                "ordering": ["group", "match_number"],
                "unique_together": {("group", "match_number")},
            },
        ),
        migrations.CreateModel(
            name="MatchScore",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "wins",
                    models.IntegerField(
                        default=0, help_text="Number of chicken dinners (display only, not counted in total)"
                    ),
                ),
                ("position_points", models.IntegerField(default=0)),
                ("kill_points", models.IntegerField(default=0)),
                ("total_points", models.IntegerField(default=0)),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="scores", to="tournaments.match"
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="match_scores",
                        to="tournaments.tournamentregistration",
                    ),
                ),
            ],
            options={
                "db_table": "tournament_match_scores",
                "ordering": ["-total_points"],
                "unique_together": {("match", "team")},
            },
        ),
    ]
