# Generated by Django 5.0 on 2025-12-30 08:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tournaments", "0009_tournament_use_groups_system_group_match_matchscore"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tournament",
            name="discord_id",
        ),
    ]
