# Generated by Django 5.0 on 2025-12-30 13:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tournaments", "0010_remove_discord_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="qualifying_teams",
            field=models.IntegerField(default=0, help_text="Number of teams that qualify from this group"),
        ),
        migrations.AddField(
            model_name="group",
            name="status",
            field=models.CharField(
                choices=[("waiting", "Waiting"), ("ongoing", "Ongoing"), ("completed", "Completed")],
                default="waiting",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="scrimregistration",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("confirmed", "Confirmed"),
                    ("rejected", "Rejected"),
                    ("withdrawn", "Withdrawn"),
                ],
                default="confirmed",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="tournamentregistration",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("confirmed", "Confirmed"),
                    ("rejected", "Rejected"),
                    ("withdrawn", "Withdrawn"),
                ],
                default="confirmed",
                max_length=20,
            ),
        ),
    ]
