# Generated by Django 5.0 on 2026-02-18 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0025_alter_group_winner_alter_match_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='live_link',
            field=models.URLField(blank=True, help_text='YouTube or streaming link for live coverage', null=True),
        ),
    ]
