# Generated by Django 5.0 on 2026-02-19 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0026_add_live_link_to_tournament'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='round_dates',
            field=models.JSONField(blank=True, default=dict, help_text="Per-round dates and mode: {'1': {'start_date': '2026-02-24', 'end_date': '2026-02-25', 'mode': 'online'}, ...}"),
        ),
    ]
