# Generated by Django 5.0 on 2025-12-28 13:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_team_losses_team_total_matches_team_wins_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hostprofile",
            name="organization_name",
        ),
        migrations.RemoveField(
            model_name="playerprofile",
            name="game_id",
        ),
        migrations.RemoveField(
            model_name="playerprofile",
            name="in_game_name",
        ),
    ]
