# Generated by Django 5.0 on 2025-12-28 17:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_remove_hostprofile_organization_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_username_change",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="username_change_count",
            field=models.IntegerField(default=0),
        ),
    ]
