# Generated by Django 5.0 on 2026-01-01 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_user_last_username_change_user_username_change_count"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamStatistics",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "tournament_wins",
                    models.IntegerField(default=0, help_text="Number of tournament victories (1st place finishes)"),
                ),
                (
                    "total_position_points",
                    models.IntegerField(default=0, help_text="Cumulative position points from all matches"),
                ),
                (
                    "total_kill_points",
                    models.IntegerField(default=0, help_text="Cumulative kill points from all matches"),
                ),
                ("total_points", models.IntegerField(default=0, help_text="Total points (position + kill)")),
                ("rank", models.IntegerField(default=0, help_text="Global leaderboard rank")),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "team",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="statistics", to="accounts.team"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Team Statistics",
                "db_table": "team_statistics",
                "ordering": ["rank"],
            },
        ),
    ]
