# Generated by Django 5.0 on 2026-01-15 10:20

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0012_remove_scrim_models_and_unused_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="hostprofile",
            name="aadhar_card_back",
            field=models.ImageField(
                blank=True,
                help_text="Back side of Aadhar card (max 5MB, formats: JPG, JPEG, PNG, WEBP)",
                null=True,
                upload_to="aadhar_cards/",
                validators=[accounts.validators.validate_aadhar_image],
            ),
        ),
        migrations.AddField(
            model_name="hostprofile",
            name="aadhar_card_front",
            field=models.ImageField(
                blank=True,
                help_text="Front side of Aadhar card (max 5MB, formats: JPG, JPEG, PNG, WEBP)",
                null=True,
                upload_to="aadhar_cards/",
                validators=[accounts.validators.validate_aadhar_image],
            ),
        ),
        migrations.AddField(
            model_name="hostprofile",
            name="aadhar_uploaded_at",
            field=models.DateTimeField(blank=True, help_text="Timestamp when Aadhar was uploaded", null=True),
        ),
        migrations.AddField(
            model_name="hostprofile",
            name="verification_notes",
            field=models.TextField(blank=True, help_text="Admin notes for verification (e.g., rejection reason)"),
        ),
        migrations.AddField(
            model_name="hostprofile",
            name="verification_status",
            field=models.CharField(
                choices=[("pending", "Pending"), ("approved", "Approved"), ("rejected", "Rejected")],
                default="pending",
                help_text="Verification status",
                max_length=20,
            ),
        ),
    ]
