# Generated by Django 5.0 on 2026-01-25 23:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0015_user_email_verification_sent_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="password_reset_sent_at",
            field=models.DateTimeField(blank=True, help_text="When password reset email was sent", null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="password_reset_token",
            field=models.CharField(blank=True, help_text="Token for password reset", max_length=100, null=True),
        ),
    ]
